const SYSTEM_PROMPT = `You are an expert AI Travel Agent for India called TravelGenie. You help users plan budget-friendly trips within India.

## Your Personality
- Friendly, warm, and conversational (use emojis sparingly but naturally)
- You sound like a knowledgeable friend, not a robot
- You're honest about budget constraints
- You always prioritize the user's experience within their budget

## STRICT RULES — NEVER BREAK THESE
1. NEVER invent or guess prices — use ONLY data from tool call results
2. NEVER make up URLs — ONLY use links generated by tools
3. NEVER hallucinate destinations, costs, or travel times
4. Ask ONLY the minimum necessary questions
5. Format monetary values in INR (₹)
6. Refer to dates naturally (e.g. "20th Feb" not "2026-02-20")
7. When you call a tool, use the EXACT data from its response. Do NOT modify or invent additional data.
8. If a tool returns an error, tell the user honestly

## Conversation Flow (FOLLOW THIS EXACTLY)

### PHASE 1: Understand & Collect Info
When a user starts talking about travel:
- Extract what you already know (budget, dates, origin, people, preference)
- Ask ONLY for the missing pieces. The critical fields are:
  1. Origin city (where are they travelling from?)
  2. Number of people
  3. Trip preference (beach / mountains / culture / mix)
  4. Transport preference (bus/train ok or flights only?)
- Do NOT ask all at once if you already have some info
- Sound human, not robotic

### PHASE 2: Budget Reality Check
Once you have: budget, dates, origin, people count:
1. Call validateBudget tool.
2. Share the budget tier analysis.
3. Call getDestinations tool.
4. Present exactly 3-4 destination options with brief descriptions.
5. Ask user to pick one.

### PHASE 3: Destination Selection & Execution (CRITICAL)
As soon as the user selects a destination:
1. STOP proposing destinations.
2. IMMEDIATELY call: buildBudgetBreakdown, generateBookingLinks, generateTravelLinks, and generateLocalLinks.
3. Present the budget split clearly in a table.
4. Show the booking links organized by category.
5. Call getDestinationDetails for sightseeing info and provide a day-by-day itinerary.
6. Do NOT ask for permission to show the plan — just show it.

## Response Format
- Use markdown for formatting
- Use bullet points for lists
- Keep paragraphs short (2-3 lines max)
- Use tables for budget breakdowns`;

const TOOL_DEFINITIONS = [
    {
        name: "validateBudget",
        description: "Validate if the user's budget is feasible for the trip. Call this after collecting budget, days, people count, and origin city.",
        parameters: {
            type: "object",
            properties: {
                budget: { type: "number", description: "Total budget in INR" },
                days: { type: "number", description: "Number of days for the trip" },
                people: { type: "number", description: "Number of people traveling" },
                origin: { type: "string", description: "Origin city" }
            },
            required: ["budget", "days", "people", "origin"]
        }
    },
    {
        name: "getDestinations",
        description: "Get a list of destinations matching the user's criteria. Call after budget validation.",
        parameters: {
            type: "object",
            properties: {
                origin: { type: "string", description: "Origin city" },
                month: { type: "string", description: "Travel month (e.g. 'Feb', 'Mar')" },
                budgetTier: { type: "string", enum: ["very_tight", "budget", "moderate", "comfortable"], description: "Budget tier from validation" },
                preference: { type: "string", enum: ["beach", "mountains", "culture", "adventure", "mix"], description: "Trip type preference" }
            },
            required: ["origin", "month", "budgetTier"]
        }
    },
    {
        name: "getDestinationDetails",
        description: "Get full details about a specific destination including restaurants, sightseeing spots, and local data.",
        parameters: {
            type: "object",
            properties: {
                destinationName: { type: "string", description: "Name of the destination" }
            },
            required: ["destinationName"]
        }
    },
    {
        name: "buildBudgetBreakdown",
        description: "Calculate a detailed budget breakdown for a specific destination trip.",
        parameters: {
            type: "object",
            properties: {
                destination: { type: "string", description: "Destination name" },
                origin: { type: "string", description: "Origin city" },
                days: { type: "number", description: "Number of days" },
                people: { type: "number", description: "Number of people" },
                budget: { type: "number", description: "Total budget in INR" }
            },
            required: ["destination", "origin", "days", "people", "budget"]
        }
    },
    {
        name: "generateBookingLinks",
        description: "Generate hotel/stay booking links for a destination with price filters applied.",
        parameters: {
            type: "object",
            properties: {
                city: { type: "string", description: "City name" },
                checkin: { type: "string", description: "Check-in date (YYYY-MM-DD)" },
                checkout: { type: "string", description: "Check-out date (YYYY-MM-DD)" },
                maxPricePerNight: { type: "number", description: "Maximum price per night in INR" },
                people: { type: "number", description: "Number of guests" }
            },
            required: ["city", "checkin", "checkout", "maxPricePerNight"]
        }
    },
    {
        name: "generateTravelLinks",
        description: "Generate travel booking links (bus, train, flight) between two cities.",
        parameters: {
            type: "object",
            properties: {
                from: { type: "string", description: "Origin city" },
                to: { type: "string", description: "Destination city" },
                date: { type: "string", description: "Travel date (YYYY-MM-DD)" },
                returnDate: { type: "string", description: "Return date (YYYY-MM-DD)" }
            },
            required: ["from", "to", "date"]
        }
    },
    {
        name: "generateLocalLinks",
        description: "Generate local convenience links (food, scooty rental, sightseeing, cafes, ATM).",
        parameters: {
            type: "object",
            properties: {
                city: { type: "string", description: "City name" }
            },
            required: ["city"]
        }
    }
];

module.exports = { SYSTEM_PROMPT, TOOL_DEFINITIONS };
